import os
import argparse
import cv2
import mediapipe as mp
import numpy as np
import pandas as pd

mp_hands = mp.solutions.hands
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles

def visualize_failed(keypoints_folder):
    failed_file = os.path.join(keypoints_folder, 'failed_paths.txt')
    
    with open(failed_file, "r") as f:
        failed_paths = f.read().splitlines()

    key = None
    index = 0
    while key != ord('q'):
        image = cv2.imread(failed_paths[index])

        # Convert to LAB color space
        lab = cv2.cvtColor(image, cv2.COLOR_BGR2LAB)
        l, a, b = cv2.split(lab)
        
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
        l_clahe = clahe.apply(l)
        
        # Merge channels
        lab_clahe = cv2.merge((l_clahe, a, b))
        
        # Convert back to RGB
        image_rgb = cv2.cvtColor(lab_clahe, cv2.COLOR_LAB2RGB)
        image = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2BGR)
        results = mp_hands.Hands(
            static_image_mode=True,
            max_num_hands=1,
            min_detection_confidence=0.5,
            model_complexity=1
        ).process(image)

        if results.multi_hand_landmarks:
            for hand_landmarks in results.multi_hand_landmarks:
                mp_drawing.draw_landmarks(
                    image,
                    hand_landmarks,
                    mp_hands.HAND_CONNECTIONS,
                    mp_drawing_styles.get_default_hand_landmarks_style(),
                    mp_drawing_styles.get_default_hand_connections_style()
                )

        cv2.imshow('Keypoints', image)

        key = cv2.waitKey(0)
        if key == ord('d'):
            index = (index + 1) % len(failed_paths)
        elif key == ord('a'):
            index = (index - 1) % len(failed_paths)

    cv2.destroyAllWindows()

def visualize_keypoints(keypoints_folder):
    keypoints_file = os.path.join(keypoints_folder, 'landmarks.csv')
    data = pd.read_csv(keypoints_file)

    key = None
    index = 0
    while key != ord('q'):
        image = cv2.imread(data.iloc[index]['image_path'])

        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        results = mp_hands.Hands(
            static_image_mode=True,
            max_num_hands=1,
            min_detection_confidence=0.5,
            model_complexity=1
        ).process(image_rgb)

        if results.multi_hand_landmarks:
            for hand_landmarks in results.multi_hand_landmarks:
                mp_drawing.draw_landmarks(
                    image,
                    hand_landmarks,
                    mp_hands.HAND_CONNECTIONS,
                    mp_drawing_styles.get_default_hand_landmarks_style(),
                    mp_drawing_styles.get_default_hand_connections_style()
                )

        cv2.imshow('Keypoints', image)

        key = cv2.waitKey(0)
        if key == ord('d'):
            index = (index + 1) % len(data)
        elif key == ord('a'):
            index = (index - 1) % len(data)

    cv2.destroyAllWindows()

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-k','--keypoints', required=True, help='Keypoint Folder (generated by to_landmark_csv.py)')
    parser.add_argument('-f', '--failed', action='store_true', help='Visualize only the failed images if this flag is set')
    args = parser.parse_args()

    if not args.failed:
        visualize_keypoints(args.keypoints)
    else:
        visualize_failed(args.keypoints)
